name: "Project Setup"
description: "Install tools using Mise"

runs:
  using: "composite"
  steps:
      - name: Configure Mise
        uses: jdx/mise-action@v4
        with:
          version: 2026.3.10
      - name: Install tools
        shell: bash
        run: mise install 
      - name: Install dependencies
        shell: bash
        run: mise run setup